### ISSUE TITLE
Confused about the training time

### ISSUE THREAD

**Issue by byeciao** [InhwanBae/ENet-SAD_Pytorch#12]
![image](https://user-images.githubusercontent.com/67251954/130737897-28ec9b0f-5619-494d-9ed3-cc454224fcb2.png)
Is it normal that it takes me 30min to train an epoch on 1080ti?
![image](https://user-images.githubusercontent.com/67251954/130738116-8e3d11a5-4eba-42ef-b226-668ad2e2de78.png)
and the test time is slow too.

**Comment by byeciao** [comment]
why the test result is so bad after training tusimple for 60k iteration?
![1630574014(1)](https://user-images.githubusercontent.com/67251954/131817504-11bf6aaa-b44d-4480-b835-c65833b27605.png)
![1630573986(1)](https://user-images.githubusercontent.com/67251954/131817523-979fa69f-3a4e-4308-adf7-f17590d9c138.png)
![1630574004(1)](https://user-images.githubusercontent.com/67251954/131817541-2acf3fe2-1dc5-40e3-9b3b-5b06a2d8078a.png)

**Comment by InhwanBae** [comment]
Hi @byeciao 
Thanks for your interest in my implementation.

In my case, It took 10 minutes per epoch with 8* 2080ti GPU. Also, it seems to be overfitted on the training set with the respect to your val_loss_seg graph. The training result of TuSimple (also CuLane) is somewhat affected by the batch size. 12~16 is suitable.

Note that the result for the TuSimple dataset was reproduced in [previous version](https://github.com/InhwanBae/ENet-SAD_Pytorch/tree/f4e07c6298cafffbfd33fbd006ebffeec99e7432). rewritten code also works exactly the same, but check it out!
