### ISSUE TITLE
안녕하세요, 코드 관련해서 몇가지 질문이 있습니다.

### ISSUE THREAD

**Issue by landkwon94** [InhwanBae/ENet-SAD_Pytorch#14]
안녕하세요! 저는 생태 관련해서 연구하고 있는 석사과정 대학원생입니다.

다름이 아니라, 어쩌다보니 lane-detection에 대해 공부하고 있는 중인데, 관련 코드를 찾던중 선생님의 코드를 찾게되어 문의드립니다.

train.py의 경우에는 CULane에 대해서만 학습을 할 수 있는 것인가요?

그거랑 또 한가지 궁금한 점이, test를 하려면 반드시 CULane이나 tuSimple 데이터셋의 format과 동일하게 만들어야 test가 가능한지 궁금합니다.

왜냐하면 제가 학습/테스트를 하고자 하는 제 이미지 사이즈가 다소 차이가 좀 있어서, 그대로 테스트해도 되는지, 그리고 어노테이션을 할 수는 있는 것인지가 궁금합니다.

좋은 코드 만들어주셔서 감사합니다!

**Comment by InhwanBae** [comment]
Hi @landkwon94

Thanks for your interest in my implementation and sorry for the late reply. 

For the first question, you can also train the TuSimple and BDD100K dataset if you change `dataset_name` in `./experiments/*/cfg.json`.
Please refer to the Training section of the `README.md` [(here)](https://github.com/InhwanBae/ENet-SAD_Pytorch/blob/master/README.md#training).

For the second question, I wrote the ENet-SAD model code to work when the input image size is multiple of 8. Nevertheless, the evaluation code works only with the gt label that matches the format of those CULane and TuSimple.

I'm closing this issue for now. Please feel free to open another issue for other questions.
