### ISSUE TITLE
BDD100K  pixel accuracy

### ISSUE THREAD

**Issue by DaniloXiao** [InhwanBae/ENet-SAD_Pytorch#16]
Thank you for your open source, it is very profitable. I would like to ask the author what is the calculation formula of the BDD100K evaluation index pixel accuracy. The formula is not listed in the paper. Is it category pixel accuracy (acc = (TP) / TP + FP)?

**Comment by InhwanBae** [comment]
Hi @DaniloXiao

Thanks for your interest in my implementation.

For the evaluation of the BDD100K dataset, I follow the [official code](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-BDD100K-Torch/train.lua#L189-L191).
In their implementation, the accuracy value is calculated within the target(ground-truth) lane area (TP/(TP+FN)). This is closer to recall than precision in the confusion matrix.

Additionally, IoU value is calculated by dividing the number of intersection pixels by unions [(here)](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-BDD100K-Torch/train.lua#L200-L210).

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Please feel free to open another issue for other questions.
