### ISSUE TITLE
training based on bdd100k?

### ISSUE THREAD

**Issue by huoguangdiandian** [InhwanBae/ENet-SAD_Pytorch#18]
Hi, I want to trian the net based on bdd100k, What should I pay attention to? For example, setting hyperparameters or Is there anything that needs to be changed in train.py. Looking forward to your reply

**Comment by InhwanBae** [comment]
Hi @huoguangdiandian ! You don't need to change `train.py`. The only thing you need to do is to modify [`cfg.json`](https://github.com/InhwanBae/ENet-SAD_Pytorch/blob/master/experiments/exp1/cfg.json#L7-L9).
```
"dataset_name": "BDD100K",
"resize_shape": [640, 360]
```
See [here](https://github.com/InhwanBae/ENet-SAD_Pytorch#training) for more detail.

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Please feel free to open another issue for other questions.
