### ISSUE TITLE
When I run demo_video.py,I got the model mismatched

### ISSUE THREAD

**Issue by zhangtingyu11** [InhwanBae/ENet-SAD_Pytorch#2]
Traceback (most recent call last):
  File "demo_video.py", line 184, in <module>
    main()
  File "demo_video.py", line 120, in main
    net.load_state_dict(save_dict['net'])
  File "/home/zty/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ENet_SAD:
	size mismatch for fc.0.weight: copying a param with shape torch.Size([128, 4500]) from checkpoint, the shape in current model is torch.Size([128, 4400]).

Can somebody help me?Thanks in advance.

**Comment by InhwanBae** [comment]
demo_video.py does not read the input image size from the config file.
[Here](https://github.com/InhwanBae/ENet-SAD_Pytorch/blob/master/demo_video.py#L14), you can solve it by changing the input size of the model you trained.

**Comment by Kaimingfan** [comment]
I have the same problem. What size did you change to？
