### ISSUE TITLE
Problems of the code

### ISSUE THREAD

**Issue by zhangtingyu11** [InhwanBae/ENet-SAD_Pytorch#3]
I check your Enet-SAD-model.py,and I found that the lane prediction branch in your code is different from the paper,can you tell me if there is any reason for this?Thanks in advance.

**Comment by jyang68sh** [comment]
@zhangtingyu11 Hi, I also have this question. Have you had any ideas? Thanks!

**Comment by InhwanBae** [comment]
Hi @zhangtingyu11 and @jyang68sh 

Thanks for your interest in my implementation. Following the [original paper(Section 3.3: Architecture Design)](https://openaccess.thecvf.com/content_ICCV_2019/papers/Hou_Learning_Lightweight_Lane_Detection_CNNs_by_Self_Attention_Distillation_ICCV_2019_paper.pdf), I adopt the same network block introduced in SCNN.

I'm now working on rearranging my implementation more similarly to the original code. If you find something different to the paper, please feel free to open another issue for other questions.

I hope this answers your questions. I'm closing this issue for now.
