### ISSUE TITLE
 bdd100k evaluation code

### ISSUE THREAD

**Issue by Hydragon516** [InhwanBae/ENet-SAD_Pytorch#4]
우선 좋은 코드를 공유해주셔서 감사합니다.

혹시 BDD100K를 평가할때 사용한 코드도 공유 가능한가요?

감사합니다.

**Comment by InhwanBae** [comment]
Hi @DaniloXiao

Thanks for your interest in my implementation and sorry for the late reply. 

I am currently unable to access the server, however, I strictly follow the [official code for BDD100K](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-BDD100K-Torch/train.lua#L189-L191). In their implementation, the accuracy value is calculated within the target(ground-truth) lane area (TP/(TP+FN)). This is closer to recall than precision in the confusion matrix. Additionally, IoU value is calculated by dividing the number of intersection pixels by unions [(here)](https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/ENet-BDD100K-Torch/train.lua#L200-L210).

I'm closing this issue for now. Congratulation on your accepted paper and please feel free to open another issue for other questions.
