### ISSUE TITLE
Tentative date to publish the testing code?

### ISSUE THREAD

**Issue by MaddyThakker** [InhwanBae/ENet-SAD_Pytorch#6]
Hi, thanks for the great PyTorch implementation. I was wondering how long it might take for you to make the testing code public? Thanks!

**Comment by OpenBanboo** [comment]
You may find helpful to refer to: https://github.com/OpenBanboo/translane/tree/main/scnn_sad_remaster

**Comment by MaddyThakker** [comment]
Thanks.
