### ISSUE TITLE
Codes for testing and evaluation

### ISSUE THREAD

**Issue by Ace-Xu** [InhwanBae/ENet-SAD_Pytorch#7]
Hey I'm very grateful for your work, and now I further need your codes for testing and evaluation, can you please provide it? Thanks   a lot!

**Comment by OpenBanboo** [comment]
You may find helpful to refer to: https://github.com/OpenBanboo/translane/tree/main/scnn_sad_remaster

**Comment by InhwanBae** [comment]
Hi @Ace-Xu 

Sorry for the late reply. I just release the code for evaluation. Check it out!
I'm closing this issue for now. Please feel free to open another issue for other questions.
